Update 0.0.53 - Fixed AttributeError: 'Classification' object has no attribute 'pred_mode' when using predictors other than all - Fixed AttributeError: 'Regression' object has no attribute 'pred_mode' when using predictors other than all